image: golang:1.12-alpine

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "dev"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG == "\d{1,2}\.\d{1,2}\.\d{1,2}"

stages:
  - test
  - build

test_api:
  stage: test
  # tags:
  #   - test
  script:
    - gofmt -e main.go

build_docker:
    image: docker:latest
    services:
    - docker:dind
    # tags:
    # - test
    # - api
    before_script:
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN $DOCKERHUB_REGISTRY
    script:
      - |
        if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
          tag=""
          echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
        else
          tag=":$CI_COMMIT_REF_SLUG"
          echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
        fi
      - docker build -t "$CI_REGISTRY_IMAGE${tag}" .
      - docker push "$CI_REGISTRY_IMAGE${tag}"
    rules:
      - if: $CI_COMMIT_BRANCH
        exists:
          - Dockerfile

