variables:
  MY_TRIGGER_TOKEN: glptt-e0e4202f71701a6bc058e2222366c09ef8c2a2cb

image: golang:latest

stages:
  - test
  - build

job:   
  stage: test   
  script:
    - 'curl --fail --request POST --form token=$MY_TRIGGER_TOKEN --form ref=master "https://gitlab.com/api/v4/projects/40037259/trigger/pipeline"'
  rules:
    - if: $CI_COMMIT_TAG

test_api:
  stage: test
  tags:
    - test
  script:
    - go build -o test .

build_docker:
  stage: build
  tags:
    - api
    - test
  script:
    - docker-compose down
    - docker-compose build
