image: golang:latest

stages:
  - test
  - build

test_api:
  stage: test
  # tags:
  #   - test
  script:
    - go build -o test .

build_docker:
  stage: build
  # tags:
  #   - api
  #   - test
  script:
    - docker-compose down
    - docker-compose build
