version: 2.1

orbs:
  slack: circleci/slack@4.4.4

jobs:
  test:
    docker:
      - image: circleci/golang:1.13.8
    steps:
      - checkout
      - run:
          name: "Testing Golang file for right syntax"
          command: "gofmt -e main.go"
      - slack/notify:
          event: pass
          custom: Failed pipeline 
  
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Login to Dockerhub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - run:
          name: Building image
          command: docker build -t $DOCKERHUB_USERNAME/test-01:latest .
      - run:
          name: Pushing to Dockerhub
          command: docker push $DOCKERHUB_USERNAME/test-01:latest
  
workflows:
  golang-api-workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}
