version: 2.1

# orbs:
#   slack: circleci/slack@3.5.5

jobs:
  test:
    docker:
      - image: circleci/golang:1.13.8
    steps:
      - checkout
      - run:
          name: Try
          command:  curl -i -X POST -d "name=check-x-header" --url https://hooks.slack.com/services/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
      - run:
          name: "Testing Golang file for right syntax"
          command: "gofmt -e main.go"
      # - slack/notify:
      #     message: "Failed notifs"
      #     color: "#42e2f4" # Optional: Assign custom colors for each notification
      #     webhook: $SLACK_WEBHOOK
  
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Login to Dockerhub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - run:
          name: Building image
          command: docker build -t $DOCKERHUB_USERNAME/test-01:latest .
      - run:
          name: Pushing to Dockerhub
          command: docker push $DOCKERHUB_USERNAME/test-01:latest
  
workflows:
  golang-api-workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}
