version: 2.1
# orbs:
#   slack: circleci/slack@4.1
jobs:
  test:
    docker:
      - image: circleci/go@1.7.1
    steps:
      - checkout
      - run:
          name: "Testing Golang file for right syntax"
          command: "gofmt -e main.go"
#       - slack/notify:
#           event: fail
#           template: basic_fail_1
  
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Login to Dockerhub
          command: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - run:
          name: Building image
          command: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:$(git rev-parse --short "$GITHUB_SHA") .
      - run:
          name: Pushing to Dockerhub
          command: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:$(git rev-parse --short "$GITHUB_SHA")
  
workflows:
  golang-api-workflow:
    jobs:
      - test
      - build
