version: 2.1
orbs:
  slack: circleci/slack@4.1
slack-fail-post-step:
  post-steps:
    - slack/notify:
        custom: |
          {
            "text": "",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "❌ *Failure* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}`"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${SLACK_WEBHOOK}"
                  }
                ]
              }
            ]
          }
        event: fail

jobs:
  test:
    docker:
      - image: circleci/golang:1.13.8
    steps:
      - checkout
      - run:
          name: "Testing Golang file for right syntax"
          command: "gofeeemt -e main.go"
      - slack/notify:
          event: fail
          template: basic_fail_1
  
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Login to Dockerhub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - run:
          name: Building image
          command: docker build -t $DOCKERHUB_USERNAME/test-01:latest .
      - run:
          name: Pushing to Dockerhub
          command: docker push $DOCKERHUB_USERNAME/test-01:latest
      - slack/notify:
          event: fail
          template: basic_fail_1
  
workflows:
  golang-api-workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}
      - slack/on-hold:
          context: slack-secrets
          requires:
            - test
            - build
